### ISSUE TITLE
Debugging Cortex-M0 Core of image containing code for both cores

### ISSUE THREAD

**Issue by misaz** [Infineon/mtb-example-psoc6-dual-cpu-empty-app#1]
I created project based on this template using ModusToolbox IDE 2.2 targeting development board CY8CKIT-062S2-43012 (MCU is CY8C624A). I want debug full image containing code for both M0 and M4 cores so I am starting debug when I have selected file in cm4_app project. I want debug M0 (not a M4) core of that full image. When I attemp start debugging (using highlighted button in red box on screenshot) I get error `Program file does not exist`. I can debug M0 core in cm0_app (but it does not include code for m4) and I can debug M4 core of cm4_app. To summarize:

- cm0_app:
  - Debug CM0 - Working ✔
- cm4_app:
  - Debug CM0 - Not working (screenshot) ❌
  - Debug CM4 - Working ✔

![obrazek](https://user-images.githubusercontent.com/2937706/100935692-b6e21f80-34f0-11eb-9d00-83c37c213bfd.png)

**Comment by rmbk19** [comment]
Hi @misaz ,

We are able to recreate the issue. Thank you for pointing this out. I will be creating an internal ticket so that the development team can evaluate this issue.

Meanwhile, you could try the following workarounds:

- Program the device using Dual-CPU_Empty_PSoC6_App.cm4_app Program (KitProg3_MiniProg4) launch.
- Debug the device using the Dual-CPU_Empty_PSoC6_App.cm0p_app Debug CM0+ (KitProg3_MiniProg4) launch.
or
- Copy the cy_m0p_image.elf and cy_m0p_image.hex files from _cm0p_app\build\<target>\Debug_ directory and place it in _cm4_app\build\<target>\Debug_ directory.
- Debug the device using the Dual-CPU_Empty_PSoC6_App.cm4_app Debug CM0+ (KitProg3_MiniProg4) launch.

Please let me know if this works.

Thanks and Regards, 
Rakshith M B
